# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9853c81f5948bb94e3b2ebb45fbc7d78"
name = "test-sq"
application_url = "https://shopify-proxy-test.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# 添加 App Proxy 所需权限
scopes = "write_app_proxy"

[auth]
redirect_urls = [
  "https://shopify-proxy-test.onrender.com/auth/callback"
]

# ⭐ App Proxy 配置
# 访问 /apps/test 时代理到 guya-uniwigs-shop
[app_proxy]
url = "/proxy"
prefix = "apps"
subpath = "test"